/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as GatesRouteImport } from './routes/gates'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SkipRouteImport } from './routes/skip'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as WeeksRouteImport } from './routes/weeks'
import { Route as WeeksIndexRouteImport } from './routes/weeks.index'
import { Route as WeeksWeekIdRouteImport } from './routes/weeks.$weekId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesRoute = GatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SkipRoute = SkipRouteImport.update({
  id: '/skip',
  path: '/skip',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeksRoute = WeeksRouteImport.update({
  id: '/weeks',
  path: '/weeks',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeksIndexRoute = WeeksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeeksRoute,
} as any)
const WeeksWeekIdRoute = WeeksWeekIdRouteImport.update({
  id: '/$weekId',
  path: '/$weekId',
  getParentRoute: () => WeeksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changes': typeof ChangesRoute
  '/gates': typeof GatesRoute
  '/interview': typeof InterviewRoute
  '/project': typeof ProjectRoute
  '/rules': typeof RulesRoute
  '/skip': typeof SkipRoute
  '/tracks': typeof TracksRoute
  '/weeks': typeof WeeksRouteWithChildren
  '/weeks/$weekId': typeof WeeksWeekIdRoute
  '/weeks/': typeof WeeksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changes': typeof ChangesRoute
  '/gates': typeof GatesRoute
  '/interview': typeof InterviewRoute
  '/project': typeof ProjectRoute
  '/rules': typeof RulesRoute
  '/skip': typeof SkipRoute
  '/tracks': typeof TracksRoute
  '/weeks/$weekId': typeof WeeksWeekIdRoute
  '/weeks': typeof WeeksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changes': typeof ChangesRoute
  '/gates': typeof GatesRoute
  '/interview': typeof InterviewRoute
  '/project': typeof ProjectRoute
  '/rules': typeof RulesRoute
  '/skip': typeof SkipRoute
  '/tracks': typeof TracksRoute
  '/weeks': typeof WeeksRouteWithChildren
  '/weeks/$weekId': typeof WeeksWeekIdRoute
  '/weeks/': typeof WeeksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changes'
    | '/gates'
    | '/interview'
    | '/project'
    | '/rules'
    | '/skip'
    | '/tracks'
    | '/weeks'
    | '/weeks/$weekId'
    | '/weeks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changes'
    | '/gates'
    | '/interview'
    | '/project'
    | '/rules'
    | '/skip'
    | '/tracks'
    | '/weeks/$weekId'
    | '/weeks'
  id:
    | '__root__'
    | '/'
    | '/changes'
    | '/gates'
    | '/interview'
    | '/project'
    | '/rules'
    | '/skip'
    | '/tracks'
    | '/weeks'
    | '/weeks/$weekId'
    | '/weeks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangesRoute: typeof ChangesRoute
  GatesRoute: typeof GatesRoute
  InterviewRoute: typeof InterviewRoute
  ProjectRoute: typeof ProjectRoute
  RulesRoute: typeof RulesRoute
  SkipRoute: typeof SkipRoute
  TracksRoute: typeof TracksRoute
  WeeksRoute: typeof WeeksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates': {
      id: '/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof GatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skip': {
      id: '/skip'
      path: '/skip'
      fullPath: '/skip'
      preLoaderRoute: typeof SkipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weeks': {
      id: '/weeks'
      path: '/weeks'
      fullPath: '/weeks'
      preLoaderRoute: typeof WeeksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weeks/': {
      id: '/weeks/'
      path: '/'
      fullPath: '/weeks/'
      preLoaderRoute: typeof WeeksIndexRouteImport
      parentRoute: typeof WeeksRoute
    }
    '/weeks/$weekId': {
      id: '/weeks/$weekId'
      path: '/$weekId'
      fullPath: '/weeks/$weekId'
      preLoaderRoute: typeof WeeksWeekIdRouteImport
      parentRoute: typeof WeeksRoute
    }
  }
}

interface WeeksRouteChildren {
  WeeksWeekIdRoute: typeof WeeksWeekIdRoute
  WeeksIndexRoute: typeof WeeksIndexRoute
}

const WeeksRouteChildren: WeeksRouteChildren = {
  WeeksWeekIdRoute: WeeksWeekIdRoute,
  WeeksIndexRoute: WeeksIndexRoute,
}

const WeeksRouteWithChildren = WeeksRoute._addFileChildren(WeeksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangesRoute: ChangesRoute,
  GatesRoute: GatesRoute,
  InterviewRoute: InterviewRoute,
  ProjectRoute: ProjectRoute,
  RulesRoute: RulesRoute,
  SkipRoute: SkipRoute,
  TracksRoute: TracksRoute,
  WeeksRoute: WeeksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
